#
# Copyright INK Labs. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:
  inkerface-listener.org1:
    container_name: inkerface-listener-org1
    image: inklabsfoundation/inkerface-listener:x86_64-0.15.8
    volumes:
      - ../config/artifacts:/work/config/artifacts
      - ../config/network-config.json:/work/config/network-config.json
      - ../config/inkchain-client-kvs_peerOrg1:/tmp/inkchain-client-kvs_peerOrg1
      - ../config/config.json:/work/config/config.json

  inkerface-explorer.org1:
      container_name: inkerface-explorer-org1
      image: inklabsfoundation/inkerface-explorer:x86_64-0.16.6
      ports:
        - 8080:8080
      volumes:
        - ../config/config.json:/work/config.json


