#
# Copyright INK Labs. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:
  inkerface-listener.org1:
    container_name: inkerface-listener-org1
    image: inklabsfoundation/inkerface-listener:x86_64-0.15.8
    volumes:
      - ../config/artifacts:/work/config/artifacts
      - ../config/network-config.json:/work/config/network-config.json
      - ../config/inkchain-client-kvs_peerOrg1:/tmp/inkchain-client-kvs_peerOrg1
      - ../config/config.json:/work/config/config.json

  inkerface-fullserver.org1:
      container_name: inkerface-fullserver-org1
      image: inklabsfoundation/inkerface-fullserver:x86_64-1.1.1
      ports:
        - 8081:8081
      volumes:
        - ../config/artifacts:/work/config/artifacts
        - ../config/network-config.json:/work/config/network-config.json
        - ../config/inkchain-client-kvs_peerOrg1:/tmp/inkchain-client-kvs_peerOrg1
        - ../config/config.json:/work/config/config.json


